commands:
  help: true
  player: true
  toggle: true
  collect: true
  spectate: true
  accept: true
  leave: true
  reload: true
  setSpawn: true
  fix: true
  fixAll: true
  fly: true
maps:
  default:
    name: "&e&lupdate the config.yml"
    icon: "glass"
    #The x, y, and z positions of the map that players will be teleported to
    spawn1:
      ==: org.bukkit.Location
      world: world
      x: 100.0
      y: 100.0
      z: 100.0
      pitch: 500.0
      yaw: 400.0
    spawn2:
      ==: org.bukkit.Location
      world: world
      x: 100.0
      y: 100.0
      z: 100.0
      pitch: 0.0
      yaw: 0.0
    #The position in the map GUI that the map will have (0-8)
    guiPos: 4 #4 is the center
text:
  help:
  - "&e&l&nDuel Commands&r"
  - "&e/duel send <name>"
  - "&7Invite a player to a settings specific duel"
  - "&e/duel toggle"
  - "&7Toggle duel invites from other players."
  - "&e/duel spectate"
  - "&7Access the duel spectate menu."
  - "&e/duel collect"
  - "&7Access your Stake Collection Bin."
  no-permission: "&eYou do not have permission to use that command!"
  invalid-map: "&cPlease choose a valid map!"
  set-spawn: "&eSpawn position updated!"
  duel-self: "&cYou can't duel yourself!"
  player-offline: "&cThat player is not online!"
  player-in-duel: "&cThat player is already in a duel!"
  in-duel: "&cYou are already in a duel!"
  requests-disabled: "&cThis player has duel requests disabled!"
  rewards-waiting: "&cYou have duel rewards waiting to be collected!"
  disable-requests: "&cDuel requests have been disabled!"
  enable-requests: "&aDuel requests have been enabled!"
  not-collected: "&cNot all winnings were collected! Try emptying your inventory."
  item-not-collected: "&cItem could not be collected! Try emptying your inventory."
  winnings-collected: "&aWinnings have been collected!"
  collect-empty: "&c&l(!) &cYour &n/duel collect&c is empty."
  not-spectating: "&cYou are not currently spectating anyone!"
  stop-spectating: "&cStopped spectating!"
  invalid-spectate: "&cThat player is not currently in a duel!"
  spectate-info: "&eType &6/duel spectate stop&e to stop spectating!"
  duel-inactive: "&cThat duel request is not active!"
  map-unavailable: "&cThat map is currently unavailable!"
  request-sent: "&eYour duel request has been sent."
  hit-30: "&e&l[/duel] &eHit the opponent in 30 seconds otherwise it will be a draw."
  hit-60: "&e&l[/duel] &eHit the opponent in 60 seconds otherwise it will be a draw."
  duel-draw: "&eDuel cancelled."
  duel-win: "&eYou have won the duel! use &6/duel collect &eto claim your winnings."
  duel-info:
    - "&b&m&l====================&6&m&l=====================&r"
    - "&r"
    - "           &8[ &6&lDUEL STARTED - FIGHT! &8]&r"
    - "                      &b&l%dueler1%&r"
    - "                 &c&l&m----&r&c&l VS &c&l&m----&r"
    - "                      &b&l%dueler2%"
    - "&r"
    - "&b&m&l====================&6&m&l=====================&r"
  close-settings: "&e&l(!) &eYou closed the &nSETTINGS&e selection."
  close-arena: "&e&l(!) &eYou closed the &nARENA&e selection."
  close-wager: "&e&l(!) &eYou closed the &nRISK INVENTORY&e selection."
  cancel-duel: "&7The duel has been cancelled."
  not-in-duel: "&cYou are not in a duel!"
  not-enabled: "&c%command% is not enabled!"
  map-invalid: "&cPlease choose a valid map!"
  spawn-updated: "&eSpawn position updated!"
  kit-none: "&a&lNone Kit"
  kit-soup: "&a&lSoup Kit"
  kit-potion: "&a&lPotion Kit"
  kit-nodebuff: "&a&lPotions (No Debuff)"
  duel-title: "&e&l[/duel]"
  versus-description: "&b&l%player1% vs %player2%"
  certificate-title: "&r&l%player%'s Death Certificate"
  certificate-lore1: "&f%player% &7was defeated in a &f1v1"
  certificate-lore2: "&7duel on &f%date% at %time%"
  certificate-lore3: "&7in the %arena%&r&7 by &f%winner%"
  collect-def: "&aItem(s) in your '/duel collect' bin!"
  won-def: "&a%player% won this duel."
  no-winner: "&7This duel has no winner (draw)."
  duel-cancelled: "&eDuel cancelled."
  collect-menu: "&8Duel Collect Bin"
  collect-item: "&e&lDuel Collect"
  collect-desc: "&7Click to collect everything"
  duel-menu: "&8Duel Settings"
  duel-settings: "&e&lConfirm Settings"
  duel-args: "&e%arg%: %enabled%"
  duel-kit: "&eKit: %kit%"
  duel-select: "&7Click to go to the Arena Selection."
  kit-menu: "&8Select a Kit"
  kit-select: "&8Click to select this kit."
  map-menu: "&8Map Settings"
  map-open: "&a&lOPEN"
  map-taken: "&e&n%player1% &evs &e&n%player2%"
  wager-menu: "&8Duel Wager"
  wager-ready: "%player%: %ready%"
  wager-accepted: "&6%player% &a&lHas accepted!"
  wager-notaccepted: "&6%player% &c&lHas not accepted!"
  wager-inventory: "&c&l%player% Inventory"
  wager-inv2: "&7Click to see your opponent's inventory"
  wager-starting: "&e&lDUEL STARTING &ein &e&n%seconds%s&r"
  wager-prepare: "&7Prepare for battle!"
  inventory-menu: "&8Inventory view"
  inventory-wagering: "&a&lWagering"