maps:
  default:
    name: "&e&lupdate the config.yml"
    icon: "glass"
    #The x, y, and z positions of the map that players will be teleported to
    spawn1:
      ==: org.bukkit.Location
      world: world
      x: 100.0
      y: 100.0
      z: 100.0
      pitch: 500.0
      yaw: 400.0
    spawn2:
      ==: org.bukkit.Location
      world: world
      x: 100.0
      y: 100.0
      z: 100.0
      pitch: 0.0
      yaw: 0.0
    #The position in the map GUI that the map will have (9x3)
    guiX: 4 #0-8
    guiY: 1 #0-2